### ISSUE TITLE
Project does not work with React 18

### ISSUE THREAD

**Issue by MWallenberg** [CagriAldemir/react-cache-buster#10]
This package has a peer dependency on React 17, which means it breaks with React >= 18. I haven't dug deepy into the code, but perhaps it can be fixed simply by updating the package.json?

**Comment by igitur** [comment]
React 18 support would be appreciated so much. I know this is open-source and I'm not entitled to anything, so I'm going to try to create a PR for this, but @CagriAldemir , if you want to do it ahead of me, please do.
