### ISSUE TITLE
[feature request] Hook for requesting a version check

### ISSUE THREAD

**Issue by MartinCura** [CagriAldemir/react-cache-buster#17]
Hi! Thanks for this simple but useful package.

Could we do a simple hook that returned a function which we could call to trigger a version check?

Currently when adding this wrapper to our (react-admin) SPA, user still has to reload the page for react-cache-buster to do its thing.

If we had a way to trigger the version check whenever, we could run it on each route change or something like that, and make sure our users (which tend to leave our app open for days) always get the freshest version.

I could try to take a crack at it though i'm not sure when i'll have the time.

Thanks!

**Comment by MartinCura** [comment]
Well decided i did have a couple of hours to kill so here it is: #18

**Comment by Z-Repo** [comment]
I think I’m a but confused. I’m also wanting my deployments to clear cache automatically with the changes upon deployment, however I’m not interested in a manual check button as described in the readme. (It does say this is done by default but that doesn’t seem to be the case.)

currently a simplified version of my code looks like this:

import CacheBuster, {useCacheBuster} from “react-cache-buster

return(
<cachebuster
{props go here}>
{usecachebuster()}
{content goes here}
</cachebuster>
);

Is this how the hook is meant to be used to update without requiring refresh?
