### ISSUE TITLE
Any option for a callback?

### ISSUE THREAD

**Issue by TaylorFoster90** [CagriAldemir/react-cache-buster#2]
Hello! Great package!

I was wondering if there is an option (or a future option) to have a callback IF the cache was cleared. Something like

```
onCacheClear={() => {})
```

Thanks again for this package! =]

**Comment by CagriAldemir** [comment]
Thanks for your support @TaylorFoster90 
I added onCacheClear callback function to new version of react-cache-buster (v0.1.6)
