### ISSUE TITLE
Version comparison according SemVer

### ISSUE THREAD

**Issue by rekomat** [CagriAldemir/react-cache-buster#3]
Hej Çağrı 

Just noticed that the version comparison does not work as expected. 

```js
// /src/CacheBuster.js: 56, Function isThereNewVersion
isThereNewVersion('1.3.0-rc.0', '1.3.0-rc.0'); // → returns true, should return false
```

A good solution could be to compare versions according to [SemVer](https://semver.org/) using a package like [`compare-versions`](https://www.npmjs.com/package/compare-versions). 

Sorry for not submitting a PR. Somehow I cannot manage to run your code locally. 🤪

Best, René

**Comment by CagriAldemir** [comment]
Thanks for your support @rekomat 
I added compare-versions package to new version of react-cache-buster (v0.1.6)

**Comment by rekomat** [comment]
Just updated to the latest versions. Thanks @CagriAldemir, have a great day!
